development:
  host: localhost:5000
  email: kyndream@gmail.com
  password: cocacola
  api_key: dae60bcafc2ca03e49abd002c48244c7d4704ded
staging:
  host: staging.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>