development:
  host: localhost:8080
  # email: john@doe.net
  # password: apassword
  api_key: 23ea9e633b999347cb83750f2ade62f7f3b3ffcc
staging:
  host: staging.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
